# Peaks at the Weeks: Nineteen Forty-nine

**January 26, 1949**

Dear friends,

The Christmas season has come and gone. Was it as joyous for you as it was for us? Our most wonderful gift was the arrival on Christmas morning of baby Linda Lou! She is a present that grows sweeter as the days go by. She weighed 8 lbs. 6 oz. was twenty inches long and is a perfect beauty. We had all been worrying if her arrival was going to interfere with other Christmas plans but if she times all her arrivals as well as she did this one, she nor her friends will have to worry. The Christmas pageant by the village school had been on Friday afternoon, then the Christmas story in pictures was shown in an outside service on Christmas eve after which we missionaries had our gift exchange and a little party. Than Linda arrived at 10:00 A.M. and that night all enjoyed the annual Christmas dinner.

The Congolese were almost as tickled as we were over it all, especially the fact that she came on noel. They all wanted to see her. Some of our people had never seen a white baby. One of the women remarked--why she leeks just like one of our babies. Their babies are white for the first few days. It is the custom to name each white person for some Christian native who has recently died. Just after one of our young couples had made all preparations to go to the Congo Christian Institute at Bolenge for their further training, the wife died in child birth. Linda Lou is now Botoka Malia in her honor.


**May 28, 1949**

Linda is growing like a weed. She has two teeth, sits alone and crawls as big as life. She absolutely refuses to stay on her blanket, I have a boy watch her to keep her on but he was gone for a minute and Claylon said he thought she would be O.K. as she was lying quietly but by the time he had put on a tie she
had gotten clear off the blanket and was scooting across the fleer. she cries so seldom that Mrs. Boyer has been declaring that she couldn't but this afternoon Linda showed her. We went down to visit the new state people for tea and everyone was saying their "hellos" and making over Linda and she really let loose and kept on until I was almost ashamed of her after having bragged about her conduct. She isn't used to crowds and even the place looked strange as we have scarcely had a chance to have her away from home.


**Sept. 13, 1949**

(From the Penn Sheraton Hotel in Philadelphia)

Hi from good old U.S.A.! We docked about noon here at Philadelphia but by the time we finished customs and got to the hotel it was nearly 5 P.M. so Ells (Lewis) and Claylon left Lil and me with all the kids and dashed off to New York for the evening. They were to see Emory Ross, pick up any mail, get our clergy permits, etc. and spend the evening with the Rosses. So Lil and I had the fun of taking all the young ones right from the heart of Africa to a restaurant. Mary Jo, at 6 1/2 should be sort of self reliant but she's all eyes and ears and can't pay much attention. Casey at 2 1/2 is impossible. Knows no fear and pays no attention to anyone. Then Mark at 13 mo. and Linda at 9 are our babies. Our first obstacle was the revolving door that Casey had to stop and examine when half way through. Red lights meant nothing to them but the red and white stripes on the barber pole across the street was a great fascination. We finally managed to get supper ordered and eaten but not without some struggles but half-way through Mary Jo says, "My, but isn't this fun and aren't we glad our husbands aren't here?" Lil has harnesses for both little boys so she harnessed them up and we 'drove' out of the restaurant. We have been wondering ever since we arrived at the hotel if people stare at us because we look as queer as we feel, if it's the children, or if we're just not used to people.

Linda Lou is a little dear. She has acted all day as if she knew something exciting was on foot and she didn't want to miss out. She hasn't been fussy but just jumps up and down and won't let us out of her sight for fear she will be left behind. She is a wonderful traveler, seems to love every minute of it and every person she sees.

We had an uneventful crossing. Just 15 days from Matadi and very wonderful weather. I'm no sailor so was sick a lot but that gave Claylon lots of experience at his housewifely duties and he came through fine. It was just the opposite with the Lewises. Ells was sick so Lil had it all to do. Still can't realize we've arrived. Can you imagine - 3 months ago yesterday we left Wema. Nothing speedy about that, is there?

(During the rest of 1949 and 1950 we were in the U.S. so there are no long letters about any of us. Since Ronnie was born in a hospital at Rochester, Indiana on Feb. 27, 1950 there is not much recorded about his earliest days or antics. It is only when we start traveling again that he comes into his own.)