# 1952

**February 11, 1952**

Guess I'd just as well start off telling you some more cute things your grandchildren do. They are the "book" craziest children I ever saw I think. Don't know what that is a sign of, if anything, but it almost gets to be a nuisance sometimes. If I so much as sit down on a chair, no matter what the time of day, and one of them sees me in they come for a story. We have read nursery rhymes until I could say them in my sleep and by now even Ronnie can recite fairly long portions of several of them. Linda does them with no coaching, scores of them. But the thing that really made his daddy swell up with pride was the other day when Ronnie exhibited his counting ability. Claylon had been helping Linda count to 5, then immediately Ronnie spoke up 6, 7. We thought it a coincidence and tried him out several times but always he had the right answer. Then the next morning Claylon said 1, 2 and Ronnie follows 3, Claylon 4, Ronnie 5, and so on up to 7 so naturally his daddy is convinced he is just smart. Some of the time lately I have been letting them come upstairs to school if they will be fairly quiet. Ronnie doesn't stay long but Linda would keep at her "studies" all morning if I would let her. One day I wanted her to go down and play and she says no, I just have to study my spelling.

Within a few months I plan to order the Calvert kindergarten course so that if she is really interested next year she can do some work. Think it may be easier to manage her that way than to insist she stay down and play outside.

Guess yon had as well know all our troubles at once. We are expecting another little Weeks about September 1!  That isn't trouble except that since I haven't quite reached the third month yet I am sick as a dog most of the time so am no help either in the work or the morale of things around here.  It is
encouraging to know that I am no ways nearly as bad off as when either of the first two were on the way. About like with Ronnie, I guess. I have been able to keep at school each morning but when our hot afternoons hit then I'm done for the day. Another 2 to 4 weeks should find me feeling fine, I hope, then maybe everything will look brighter. We're happy about the baby, of course, for Ronnie will be 2 1/2 by then and then maybe we won't be traveling with a tiny baby again.

**April 12, 1952**

It is so hot and dry that one can hardly get through the afternoons and by night when the children are in bed are so exhausted from putting up with the heat and it's usually still hot, that all one can do is go to bed. The heat is bothering blacks and whites alike and causing more sickness than the doctors have most ever seen. There has been an epidemic of dysentery that really lays them out.  It is tropical disease but up until last year they say we had never been bothered around here. Last year while the Horners were gone and the nurses ran out of medicine several patients died. There have been no deaths this year but at the last count there had been about 75 cases treated at the hospital. There were 25 from the boys' house in one day. It's from the low water, for the folks drink fron the streams and when the streams are badly contaminated and the water isn't high enough to keep moving on, they get sick. Claylon has been boiling the water for the school boys lately and that has helped.

Then there have been a lot of cases of polio. There have been three of the nurses' children at the hospital had it just recently and several others from near here—even an adult or two. We are keeping all the children away from crowds as much as we can.

I told you earlier about the measles. Marjorie gave all the children shots and though ours both had the measles, neither was very sick so guess they really helped. They weren't even very cross but were broken out like genuine measles.

We acquired a new member of the household this A.M. A Belgian couple are leaving and wanted a good home for their dog. When they had visited with us we noticed that Ronnie was making up to the dog especially well. (He has always been a little afraid of dogs.) I had always been opposed to such young children having dogs but what could I say when he was loving it and when I was asked for my opinion in front of all the visitors and family. So-- it is a lovely one, about three years old, out of its baby ways and well house broken, though is definitely a house dog. Since it understands only French, both Ronnie and Linda are beginning to talk to it in French. Ronnie suggested this afternoon that it take its nap in bed with him but we quickly vetoed that. Since it slept under one of their beds, don't know how long it will be till we find them all curled up together.

Linda has been picking up a lot of her elders' expressions. She rattles off "for goodness sakes" and "my gracious" just like her mother. Then she has Marjorie's "it's simply wonderful" down pat. She says, "My gracious, can't you see that I can't do that right now. I am simply too busy." But Ronnie is the one with a mind of his own. we have been trying, though not so very hard, to impress correct bathroom procedures on him. He goes willingly and alone IF it is all his idea but just let someone else suggest it! One day while Marjorie was here he grabbed himself so I rushed him to the bathroom and Very Much against his will he did everything right. Then he threw himself and had a regular tantrum. "I didn't want to go on the potty!" He must have yelled for 5 min. Marjorie repeated that to Howard who, of course, thought it about the funniest thing he ever heard of (since it wasn't his child, I expect.) They used to think Billy was abnormal with lots of tantrums but it looks perfectly OK to them in Ronnie. Another one he has, Dad, is sometimes at the table when he doesn't want to say "Thank you". He's not like you in not being thankful because he doesn't want the food, he just wants it right now and not after time for a blessing. Sometimes halfway through the meal he is ready for time out.


**May 13, 1952**

My spirits as well as my physical condition seem to have revived with the coming of cooler weather. Hope its a lasting condition.  My school will be out in less than a month and I am hoping to get a lot of housework done as well as other things. I have an assignment to write another Lonkundo text, I need to take lots of pictures, l  want to work in the yard, paint some furniture, write a form letter, and would like to take three or four days off to go with Claylon into the back country for a look into schools there and a bit of a vacation. Then we should start school by the middle of July since we'll have to take a few days off during the fall.

The children are as cute and noisy as ever. Linda knows we are going to have a babv one of these days and is convinced that it is to be a brother. We were discussing names today and I was saying that if it is a girl Hilda wants her called Susan and Linda pipes up "And if it's a boy it will be called Tommy." She says it's all right for Ronnie to have a baby sister but she wants a baby brother.

I am being besieged with questions now. Linda picks up a book – "Now, Mommie, who makes that book? Who makes this picture?" Tonight at supper, "Where did we get this pineapple?" "Well, it grew in the dirt and sand." "What is sand?" "What makes flowers grow?" I say, "God" knowing I'm letting myself in for something. "Where is God? How does He make the flowers grow?" Then I wish she had a grandmother or two here to help me out. The books I have read don't seem to give the answers, they just say all questions should have sensible answers. Oh, me.

Ronnie has taken up Randy's old trick of calling his daddy by his name. In the morning it's "Where's Claylon? Claylon, breakfast is ready. CLaylon, read me a story." As Claylon says, if everyone could say his name as plainly as Ronnie surely we wouldn't get so many letters addressed incorrectly. I heard Linda tell him one day, "That's Daddy." But Ronnie get her with "But his name is Claylon." Linda's favorite expression this week is, "Oh Mother, I'm sooooooooooooo--excited!"


**May 27, 1952**

I thought I'd get this done before the noisiest half of the family got up fron his nap but no such luck. Linda has been quietly sitting on the floor drawing but now she tells me, "My little Ronnie boy is getting up!" Sometimes she is very motherly and condescending to him and takes great delight in pleasing hin but the spells are usually short lived. She says now that he is such a happy little boy!

They are messily having iced drinks in "breakable" glasses. A few days ago they grew up and any more are highly insulted to be served in their tin plates and plastic glasses. As Linda says, I'm growing bigger
every day, and now I'm big enough for a "breakable" plate. Of course, whatever she does is good enough for little brother.


**June 3, 1952**

Ronnie and Hal, Jr. play outside all morning long until they are both so tired they can hardly eat lunch. Ronnie is going to miss Hal, Jr. for they leave July 3 and they are real good playmates. Hal, Jr. is just 4 months younger than Ronnie though a lot smaller. He holds his own so sometimes we hear some real squalls but not too often. Linda is more prone to play by herself.

She is quite interested with the new arrival. When asked what she wants, she says, "A baby brother." Well, what if it's a sister? "Oh, Ronnie may have a sister but I want a brother!" Of course, their daddy thinks they are real cute and especially when Linda begins acting subtle to get her way. The other day I was rushing around from one job to another when she says, "Mommy, aren't you awfully tired?" I admitted I was getting that way.  Her comeback was, "I just thought so. Now you come right over here and sit down
on this nice soft couch and read me a story!" So what could I do?


**June 30, 1952**

My 'vacation' is nearly over—2 more weeks to go, and I am going to have to keep moving or I won't get everything done that I had planned. I haven't done too badly though for took out some days whan I just was plain lazy and didn't do a thing. I am so anemic that I take iron pills all the time and still am on the low borderline. Then my blood pressure is so low that Marjorie says its a wonder I cam move at all. Most of the time, though, I feel real good and when I do have sometimes overdone the work, such as housecleaning, then have to take it easy for awhile.

Horners had a doctors' convention here over last week end and that meant entertaining for us, too. Since the Keane Watsons stayed here we were delighted to have them. Then Bakers from Mondombe were here, too, for several meals. The others were Belgians. Anyway I had wanted to clean house so thought this was a good goal to set to get it done before they came. We just about made it but it took some doing. It was amazing the amount of dirt we got out. I guess it was sort of like spring housecleaning at home but one would think that with hired help all the time we could at least keep the house clean but they don't even see cobwebs and dust unless they have their noses stuck in them. After spending several days in the kitchen, Eale told me one day, "I just don't like this." I asked him why not, if he didn't like to work in a clean kitchen or if he just didn't like to clean it. But he just laughed so I still don't know. Of course, compared to the way they live we must seem too particular for words. He is clean about his work and keeps the kitchen in good enough shape generally but his cupboards get as messy as they do for any of us and he just can't be bothered with cleaning them until we make an issue of it.

I am enclosing a picture that Linda cut out of her color book. I thought it was pretty good for a 3 1/2 year old without any help whatsoever. She gets terribly provoked when she doesn't do a good job of following the lines. She still sucks her thumb but I think that is about her worst habit. I wish she would quit but we have tried all sorts of talk and persuasion and nothing helps though she does often promise that when the new baby comes she won't do it any more so it won't learn how!

This is the last week of Claylon's school until the first of August. He is so glad to have it out and so am I. He can't keep up this pace just on and on. Now with Sat. classes there is no break whatsoever for him. He is up at 5:30 every morning. Sunday maybe it's 6, and stays right on the job until 6:30 at night. Then goes to church 3 nights a week, usually works int the office afterwards or has native palavers until lately he hasn't been going to bed until 10:30 or 11:00. I believe the pressure is worse than it has ever been and we can see no hope for its getting better. This next term of school he'll have that as usual and any evangelistic work and palavers that come up. Heimers leave this Thursday and Davises, who will be new to the work can't possibly get here until in January.

We are planning to make one short trip into the back country together and then he is going to make a long one by himself where he will be riding his bike a lot and won't have all the teachers and pupils, too, on his neck every day.


**July 23, 1952 (Bofanya)**

We are out on my vacation so I'll begin by starting a letter to you. We came out ot this village this morning and plan to stay for two nights. The children are home with Marjorie so it's a real vacation for me.