# 1952

## February

### February 11, 1952

Guess I'd just as well start off telling you some more cute things your grandchildren do. They are the "book" craziest children I ever saw I think. Don't know what that is a sign of, if anything, but it almost gets to be a nuisance sometimes. If I so much as sit down on a chair, no matter what the time of day, and one of them sees me in they come for a story. We have read nursery rhymes until I could say them in my sleep and by now even Ronnie can recite fairly long portions of several of them. Linda does them with no coaching, scores of them. But the thing that really made his daddy swell up with pride was the other day when Ronnie exhibited his counting ability. Claylon had been helping Linda count to 5, then immediately Ronnie spoke up 6, 7. We thought it a coincidence and tried him out several times but always he had the right answer. Then the next morning Claylon said 1, 2 and Ronnie follows 3, Claylon 4, Ronnie 5, and so on up to 7 so naturally his daddy is convinced he is just smart. Some of the time lately I have been letting them come upstairs to school if they will be fairly quiet. Ronnie doesn't stay long but Linda would keep at her "studies" all morning if I would let her. One day I wanted her to go down and play and she says no, I just have to study my spelling.

Within a few months I plan to order the Calvert kindergarten course so that if she is really interested next year she can do some work. Think it may be easier to manage her that way than to insist she stay down and play outside.

Guess yon had as well know all our troubles at once. We are expecting another little Weeks about September 1!  That isn't trouble except that since I haven't quite reached the third month yet I am sick as a dog most of the time so am no help either in the work or the morale of things around here.  It is
encouraging to know that I am no ways nearly as bad off as when either of the first two were on the way. About like with Ronnie, I guess. I have been able to keep at school each morning but when our hot afternoons hit then I'm done for the day. Another 2 to 4 weeks should find me feeling fine, I hope, then maybe everything will look brighter. We're happy about the baby, of course, for Ronnie will be 2 1/2 by then and then maybe we won't be traveling with a tiny baby again.

## April

### April 12, 1952

It is so hot and dry that one can hardly get through the afternoons and by night when the children are in bed are so exhausted from putting up with the heat and it's usually still hot, that all one can do is go to bed. The heat is bothering blacks and whites alike and causing more sickness than the doctors have most ever seen. There has been an epidemic of dysentery that really lays them out.  It is tropical disease but up until last year they say we had never been bothered around here. Last year while the Horners were gone and the nurses ran out of medicine several patients died. There have been no deaths this year but at the last count there had been about 75 cases treated at the hospital. There were 25 from the boys' house in one day. It's from the low water, for the folks drink fron the streams and when the streams are badly contaminated and the water isn't high enough to keep moving on, they get sick. Claylon has been boiling the water for the school boys lately and that has helped.

Then there have been a lot of cases of polio. There have been three of the nurses' children at the hospital had it just recently and several others from near here—even an adult or two. We are keeping all the children away from crowds as much as we can.

I told you earlier about the measles. Marjorie gave all the children shots and though ours both had the measles, neither was very sick so guess they really helped. They weren't even very cross but were broken out like genuine measles.

We acquired a new member of the household this A.M. A Belgian couple are leaving and wanted a good home for their dog. When they had visited with us we noticed that Ronnie was making up to the dog especially well. (He has always been a little afraid of dogs.) I had always been opposed to such young children having dogs but what could I say when he was loving it and when I was asked for my opinion in front of all the visitors and family. So-- it is a lovely one, about three years old, out of its baby ways and well house broken, though is definitely a house dog. Since it understands only French, both Ronnie and Linda are beginning to talk to it in French. Ronnie suggested this afternoon that it take its nap in bed with him but we quickly vetoed that. Since it slept under one of their beds, don't know how long it will be till we find them all curled up together.

Linda has been picking up a lot of her elders' expressions. She rattles off "for goodness sakes" and "my gracious" just like her mother. Then she has Marjorie's "it's simply wonderful" down pat. She says, "My gracious, can't you see that I can't do that right now. I am simply too busy." But Ronnie is the one with a mind of his own. we have been trying, though not so very hard, to impress correct bathroom procedures on him. He goes willingly and alone IF it is all his idea but just let someone else suggest it! One day while Marjorie was here he grabbed himself so I rushed him to the bathroom and Very Much against his will he did everything right. Then he threw himself and had a regular tantrum. "I didn't want to go on the potty!" He must have yelled for 5 min. Marjorie repeated that to Howard who, of course, thought it about the funniest thing he ever heard of (since it wasn't his child, I expect.) They used to think Billy was abnormal with lots of tantrums but it looks perfectly OK to them in Ronnie. Another one he has, Dad, is sometimes at the table when he doesn't want to say "Thank you". He's not like you in not being thankful because he doesn't want the food, he just wants it right now and not after time for a blessing. Sometimes halfway through the meal he is ready for time out.

## May

### May 13, 1952

My spirits as well as my physical condition seem to have revived with the coming of cooler weather. Hope its a lasting condition.  My school will be out in less than a month and I am hoping to get a lot of housework done as well as other things. I have an assignment to write another Lonkundo text, I need to take lots of pictures, l  want to work in the yard, paint some furniture, write a form letter, and would like to take three or four days off to go with Claylon into the back country for a look into schools there and a bit of a vacation. Then we should start school by the middle of July since we'll have to take a few days off during the fall.

The children are as cute and noisy as ever. Linda knows we are going to have a babv one of these days and is convinced that it is to be a brother. We were discussing names today and I was saying that if it is a girl Hilda wants her called Susan and Linda pipes up "And if it's a boy it will be called Tommy." She says it's all right for Ronnie to have a baby sister but she wants a baby brother.

I am being besieged with questions now. Linda picks up a book – "Now, Mommie, who makes that book? Who makes this picture?" Tonight at supper, "Where did we get this pineapple?" "Well, it grew in the dirt and sand." "What is sand?" "What makes flowers grow?" I say, "God" knowing I'm letting myself in for something. "Where is God? How does He make the flowers grow?" Then I wish she had a grandmother or two here to help me out. The books I have read don't seem to give the answers, they just say all questions should have sensible answers. Oh, me.

Ronnie has taken up Randy's old trick of calling his daddy by his name. In the morning it's "Where's Claylon? Claylon, breakfast is ready. CLaylon, read me a story." As Claylon says, if everyone could say his name as plainly as Ronnie surely we wouldn't get so many letters addressed incorrectly. I heard Linda tell him one day, "That's Daddy." But Ronnie get her with "But his name is Claylon." Linda's favorite expression this week is, "Oh Mother, I'm sooooooooooooo--excited!"

### May 27, 1952

I thought I'd get this done before the noisiest half of the family got up fron his nap but no such luck. Linda has been quietly sitting on the floor drawing but now she tells me, "My little Ronnie boy is getting up!" Sometimes she is very motherly and condescending to him and takes great delight in pleasing hin but the spells are usually short lived. She says now that he is such a happy little boy!

They are messily having iced drinks in "breakable" glasses. A few days ago they grew up and any more are highly insulted to be served in their tin plates and plastic glasses. As Linda says, I'm growing bigger
every day, and now I'm big enough for a "breakable" plate. Of course, whatever she does is good enough for little brother.

## June

### June 3, 1952

Ronnie and Hal, Jr. play outside all morning long until they are both so tired they can hardly eat lunch. Ronnie is going to miss Hal, Jr. for they leave July 3 and they are real good playmates. Hal, Jr. is just 4 months younger than Ronnie though a lot smaller. He holds his own so sometimes we hear some real squalls but not too often. Linda is more prone to play by herself.

She is quite interested with the new arrival. When asked what she wants, she says, "A baby brother." Well, what if it's a sister? "Oh, Ronnie may have a sister but I want a brother!" Of course, their daddy thinks they are real cute and especially when Linda begins acting subtle to get her way. The other day I was rushing around from one job to another when she says, "Mommy, aren't you awfully tired?" I admitted I was getting that way.  Her comeback was, "I just thought so. Now you come right over here and sit down
on this nice soft couch and read me a story!" So what could I do?

### June 30, 1952

My 'vacation' is nearly over—2 more weeks to go, and I am going to have to keep moving or I won't get everything done that I had planned. I haven't done too badly though for took out some days whan I just was plain lazy and didn't do a thing. I am so anemic that I take iron pills all the time and still am on the low borderline. Then my blood pressure is so low that Marjorie says its a wonder I cam move at all. Most of the time, though, I feel real good and when I do have sometimes overdone the work, such as housecleaning, then have to take it easy for awhile.

Horners had a doctors' convention here over last week end and that meant entertaining for us, too. Since the Keane Watsons stayed here we were delighted to have them. Then Bakers from Mondombe were here, too, for several meals. The others were Belgians. Anyway I had wanted to clean house so thought this was a good goal to set to get it done before they came. We just about made it but it took some doing. It was amazing the amount of dirt we got out. I guess it was sort of like spring housecleaning at home but one would think that with hired help all the time we could at least keep the house clean but they don't even see cobwebs and dust unless they have their noses stuck in them. After spending several days in the kitchen, Eale told me one day, "I just don't like this." I asked him why not, if he didn't like to work in a clean kitchen or if he just didn't like to clean it. But he just laughed so I still don't know. Of course, compared to the way they live we must seem too particular for words. He is clean about his work and keeps the kitchen in good enough shape generally but his cupboards get as messy as they do for any of us and he just can't be bothered with cleaning them until we make an issue of it.

I am enclosing a picture that Linda cut out of her color book. I thought it was pretty good for a 3 1/2 year old without any help whatsoever. She gets terribly provoked when she doesn't do a good job of following the lines. She still sucks her thumb but I think that is about her worst habit. I wish she would quit but we have tried all sorts of talk and persuasion and nothing helps though she does often promise that when the new baby comes she won't do it any more so it won't learn how!

This is the last week of Claylon's school until the first of August. He is so glad to have it out and so am I. He can't keep up this pace just on and on. Now with Sat. classes there is no break whatsoever for him. He is up at 5:30 every morning. Sunday maybe it's 6, and stays right on the job until 6:30 at night. Then goes to church 3 nights a week, usually works int the office afterwards or has native palavers until lately he hasn't been going to bed until 10:30 or 11:00. I believe the pressure is worse than it has ever been and we can see no hope for its getting better. This next term of school he'll have that as usual and any evangelistic work and palavers that come up. Heimers leave this Thursday and Davises, who will be new to the work can't possibly get here until in January.

We are planning to make one short trip into the back country together and then he is going to make a long one by himself where he will be riding his bike a lot and won't have all the teachers and pupils, too, on his neck every day.

## July

### July 23, 1952 (Bofanya)

We are out on my vacation so I'll begin by starting a letter to you. We came out ot this village this morning and plan to stay for two nights. The children are home with Marjorie so it's a real vacation for me. I guess it's the first time I've been away from them since we went to London for even as much as a day or part of a day.

They both seemed so thrilled with the possibility of sleeping at Aunt Marjorie's that they didn't mind our leaving at all. I though there might be trouble at the last but no way. They both kissed us, waved good-bye and then ran to play as if New, that's over.

I started the children's school again last week and Linda began 'school' too now so she is really very 'busy'. Actually her kindergarten is no different from what we were doing except in her eyes. She draws, colors, cuts out, pastes, uses modeling clay and as soon as I have the courage to introduce it will have poster paints. This leaves Ronnie along of a morning except that Linda usually gets tired by 10 A.M. and willingly joins him. I was afraid he'd cause trouble but on the contrary he has been having a wonderful time with two little native boys who come up every morning to play with him. They are just his age – one is the preacher's boy and the other's a teacher's.

When I knew he was going to be alone so much I asked if there were any little boys who would like to come up to play. On Sunday about two weeks ago a mother brought her little boy up to see if he could come. The family is one of our best back country leaders - he is a teacher-evangelist. They have lost several babies because the mother can't feed them enough. She now has a baby eight months old that Horners have been giving milk all the time. The little boy, just exactly Ronnie's age, had been mission fed, too, and was a little husky. I agreed he could come. That afternoon Marjorie and I were out on the road when we met the daddy come in from his village to get the family as Marjorie had agreed the baby was old enough to go home whenever they wanted to leave so that took care of the play. Anyway just two weeks later the father came carrying the little boy in to the hospital with something terribly wrong. Horners thought it was a n intestinal obstruction that happens in perfectly healthy children but causes death unless operated immediately. Howard operated but instead of finding the type of thing he expected, found an obstruction but it was from som very bad infection. They said as if something poison had reached there, though it was local enough they couldn't figure out how it could have gotten there without affecting the stomach. We were all quite concerned about the little fellow and quite as they expected, he died last evening. Their home village is here in Bofanya though he had been teaching in another village nearby. The father thinkshe knows the cause of the death.

He found the heathens in the village where he was teaching smoking "hemp" marajuana and did what he is supposed to – reported them to the state man who put them in prison. He says often the families get revenge by grabbing a child and giving it some of their heathen medicine – poison, of course. Marjoirie and Howard agree that this is very likely what happened.

I wanted to come out here to visit the school and just sort of get the feel of real village life again so that's what I plan to do tomorrow. Claylon may have some baptisms but hopes mostly to get in some hunting and real recreation.

July 29 – Tuesday A.M. While Eale finishes preparing breakfast I'll add a note tho. I hear trouble in the Jr. Dept. Ronnie usually gets up early 5 to 5:30 happy as a lark but this A.M. he is cross as a bear.

We got back Fri. night and it was good to get home though guess everything ran smoothly in our absence. Marjorie says a piece of chocolate candy will settle any difficulty in our family – from Ronnie's wanting Mommy at bedtime to a noisy quarrel. Howard says he thinks we should ask for a living supplement to feed our two. They all marvel at how much they eat. Bill and Norma always have to be coaxed but not these!

Linda asked me the other day to draw her a rooster. I was too busy at the time besides the fact I can't draw anyway, even a good looking rooster so I put her off by telling her to go to her daddy for that was more in his department. A few minutes later she came up to me and says, "Mommy, just what is your department?" There she had me.

A few days ago at the table I heard Ronnie saying something over and over almost to himself and learned he was saying "Norma goat, Norma goat." When I plied for an explanation Linda told me, "Well, you know there are Billing Goats so Ronnie thinks there are Norma Goats, too."

One can't even use the old spelling system with them any more for Linda, at least, is sure to ask now just what are you spelling? One day at mealtime I said – for daddy's ears alone – I guess we won't have any c-a-k-e for dinner today when Linda pipes up, "I guess I want some c-a-k-cake for dinner! They got it."

## August

### August 20, 1952

Ronnie's chief occupation now is to gather caterpillars. Last night some fell out of his pocket at the supper table on to his plate before we could get them out of the way. He has no inhibitions about them and told me one day after his nap that he had a bucket full of worms to take to bed with him and that his daddy would not let him! He always thinks they need a bath when he does. Right now he is "Daddy's Boy". For several days he simply refused to let me do a thing for him which didn't make me mad at all. I said I sort of hope the phase lasted but it is already passing.

I am desperately busy. There was a while when I felt like I simply did not have time to have a baby but am getting things taken care of so that maybe it will be OK to spend at least a few days in bed.

## September

### September 9, 1952

Your latest grandson put in his appearance last Saturday A.M., September 6th at 8:00 A.M. He is Thomas Claylon popularly known as Tommy. He didn't quite keep up with his brother and sister in that he only weighed in at 8lbs 2 oz. Even so, think he'll make the grade! He, his mommy, and all the family are doing nicely. This is the first peaceful moment that there has been to write. Since mail goes tomorrow we decided that was as quick a way as any to let you know what he arrived on schedule.

Ronnie and Linda are now quite pleased and want to see, feel, feed and play with him all the time. Sometime ago Linda had changed her mind and decided she wanted a Susan, so far a little while she was disappointed as she seemed to have her heart set on Susan. But yesterday she accepted the change by saying, "Our next baby will be Susan, won't it, Mommy?"

Tommy may or may not look like the other babies. I can't even remember except he has one very decided difference – he has quite a crop of dark brown hair! He at this stage – 3 1/2 days is quite contented and is making his schedule to please us. (The dark hair didn't last.)

The mail came yesterday with 3 bundles of magazines from you and the gift box of dresses! Wasn't that wonderful timing – just when I could read a bit and I'll have something new when I get going. Also before my birthday. The package came in just 2 months and had no duty so that makes it extra special. It could well have had four or five dollars on it and parcel post usually takes 4 months now so it worked out fine.

This has been a real three-ring circus with very little change in sight though everything has worked out better than expected. I wrote we didn't expect help. That day Howard was in Boende and who should be there by plane that same day but Stobie. Remember Miss Stober was with me for Linda's birth and there's nobody better to have around. We rejoiced exceedingly. The next evening V.G. and A.C. Cuppy arrived from Monieka with her sick in bed with nausea. You may remember she is the one who had to go home beofre with the same trouble. Dr. Watson who is the doctor at Monieka thinks its all in your head so he wasn't doing anything for her. At 2 1/2 months when she arrived here she had lost 20lbs and was in bed. So she stayed here with little Dwight – 18 months – while A.C. went back to Monieka and packed up. They are due for furlough anyway so are leaving Thursday from Boende right to New York by plane. They, with Stobie, have all been at our house, upstairs, all the time. Then the Belgian woman had her baby O.K. on Tuesday before Tommy came on Saturday and as she hadn't much help Stobie nursed her. Though the delivery was at Horners I came home Saturday P.M. so you can imagine the confusion here Sunday and Monday – 9 people – 4 children from 3 1/2 to 1 day, 2 bed patients, one up and one downstairs, with 2 men and one nurse in attendance. 'Twas a gay time but as I said I'm doing fine. Still enjoying the bed for the most part.

Cuppy's leave Thursday but that same day the Tillers from Lotumbe are to arrive with their two school age children. Marilyn and Herbie are to live with us and go to school with Bill and Norma for 3 or 4 months anyway. If I haven't told you about that I'll have to do it later. They are older so won't be any trouble!! Herbie is 10 or 11 and Marilyn is about two years older.

## October

### October 13, 1952

I have no illusions about getting anything done on this as it is just 15 minutes till time to go to school and I have dinner to plan beside I heard Tommy wailing meaning something must be done for him. I suppose I have been this busy before but I sure can't remember when. 5 children plus a school teaching job. Whew!

In re-reading your letters, Mom, I see you hoped we would have either a peaceable little boy or girl. We have a little boy, all right, but I wouldn't say he was any more peaceful than the other one was and, if you remember, his daddy thought he was well nigh impossible at times. I guess he is ordinarily good but he doesn't sleep any 20 to 22 hours a day as the books advocate for the first few weeks. I guess the most noticeable thing about it is that he seems most apt to cry during our supposedly rest hour after dinner, or about 10 at night.

knew he vas Yoing to be alone so much I asked if there were any
lfttle boys who would 11ke to come up to play,
a mother brought her little boy up to see if he could come. Tbe fewily 1s one of our best back country leaders- he fsa teacher-evangelist They have
lost several babies because the can't feed thea enougb, She nov has a baby eight nont hs old that Horners have been giving milk all the time,
The little boy, just exactly Ronnie' had been mission fed, toos and was
they wanted to leave so that took care of the play, Anyway just two weeks later the father caue carrying the little boy in to the hospital with sowe thing terribly Horners thought it was an intestinal obstruction that bappens in perfectly bealthy children but mauses death unless operated inmediately,
a little busky, I agreed he could come
Thit afternoon Marjorle and I were the road when we net the daddy coming in from his v1llage to get the
out on
family as Marjorie had agreed the ba by was old enough to go home whenever
Howard operated but instead of finding
obstruction but it was from some very bed infection,
On Sunday about tvo weeks ago
the type thing be expected, found an
They said as if ometbing thougb it was local enough they coulda't figure out
poison bed reached there,
how it could have gotten there without affecting
quite cor.cerned about the l1ttle fellov and quite as they
Ve were all expected. he died
Their home village is here in Bofanya though he bad beep teach-
last evening,
1ng in another village near by. death